//////////////////////////////////////////////////
// autogenerated

#ifndef _ANIMZ__HDR_H
#define _ANIMZ__HDR_H

#include <stdint.h>

#define ANIMZ_SWAMP          0x00
#define ANIMZ_SWAMP_2        0x01
#define ANIMZ_DIAMOND        0x02
#define ANIMZ_DIAMOND_2      0x03
#define ANIMZ_DIAMOND_3      0x04
#define ANIMZ_DIAMOND_4      0x05
#define ANIMZ_DIAMOND_5      0x06
#define ANIMZ_DIAMOND_6      0x07
#define ANIMZ_DIAMOND_7      0x08
#define ANIMZ_DIAMOND_8      0x09
#define ANIMZ_DIAMOND_9      0x0a
#define ANIMZ_DIAMOND_A      0x0b
#define ANIMZ_DIAMOND_B      0x0c
#define ANIMZ_DIAMOND_C      0x0d
#define ANIMZ_DIAMOND_D      0x0e
#define ANIMZ_ALPHA          0x0f
#define ANIMZ_ALPHA_2        0x10
#define ANIMZ_BLUEGHOS       0x11
#define ANIMZ_DEICO          0x12
#define ANIMZ_DEICO_2        0x13
#define ANIMZ_FORCEF94       0x14
#define ANIMZ_FORCEF94_2     0x15
#define ANIMZ_FORCEF94_3     0x16
#define ANIMZ_FORCEF94_4     0x17
#define ANIMZ_FORCEF94_5     0x18
#define ANIMZ_FORCEF94_6     0x19
#define ANIMZ_FORCEF94_7     0x1a
#define ANIMZ_FORCEF94_8     0x1b
#define ANIMZ_INSECT1        0x1c
#define ANIMZ_INSECT1_2      0x1d
#define ANIMZ_LUTIN          0x1e
#define ANIMZ_LUTIN_2        0x1f
#define ANIMZ_MANKA          0x20
#define ANIMZ_MANKA_2        0x21
#define ANIMZ_MAXKILLER      0x22
#define ANIMZ_OCTOPUS        0x23
#define ANIMZ_OCTOPUS_2      0x24
#define ANIMZ_OOO            0x25
#define ANIMZ_OOO_2          0x26
#define ANIMZ_TEDDY93        0x27
#define ANIMZ_TEDDY93_2      0x28
#define ANIMZ_VAMPLANT       0x29
#define ANIMZ_VAMPLANT_2     0x2a
#define ANIMZ_YAHOO          0x2b
#define ANIMZ_YAHOO_2        0x2c
#define ANIMZ_YIGA           0x2d
#define ANIMZ_YIGA_2         0x2e
#define ANIMZ_YELKILLER      0x2f
#define ANIMZ_YELKILLER_2    0x30
#define ANIMZ_ORB            0x31
#define ANIMZ_ORB_2          0x32
#define ANIMZ_ORB_3          0x33
#define ANIMZ_ORB_4          0x34
#define ANIMZ_TRIFORCE       0x35
#define ANIMZ_TRIFORCE_2     0x36
#define ANIMZ_TRIFORCE_3     0x37
#define ANIMZ_TRIFORCE_4     0x38

#endif
