//////////////////////////////////////////////////
// autogenerated

#ifndef _ANNIE__HDR_H
#define _ANNIE__HDR_H

#define ANNIE_ANNIE2         0x00
#define ANNIE_ANNIE2_2       0x01
#define ANNIE_ANNIE2_3       0x02
#define ANNIE_ANNIE2_4       0x03
#define ANNIE_ANNIE2_5       0x04
#define ANNIE_ANNIE2_6       0x05
#define ANNIE_ANNIE2_7       0x06
#define ANNIE_ANNIE2_8       0x07
#define ANNIE_ANNIE2_9       0x08
#define ANNIE_ANNIE2_A       0x09
#define ANNIE_ANNIE2_B       0x0a
#define ANNIE_ANNIE2_C       0x0b
#define ANNIE_ANNIE2_D       0x0c
#define ANNIE_ANNIE2_E       0x0d
#define ANNIE_ANNIE2_F       0x0e
#define ANNIE_ANNIE2_10      0x0f
#define ANNIE_ANNIE2_11      0x10
#define ANNIE_ANNIE2_12      0x11
#define ANNIE_ANNIE2_13      0x12
#define ANNIE_ANNIE2_14      0x13

#endif
