//////////////////////////////////////////////////
// autogenerated

#ifndef _SPRTYPES__H
#define _SPRTYPES__H

#define TYPE_NONE 0xff

#define TYPE_BACKGROUND          0x00
#define TYPE_STOP                0x01
#define TYPE_PLAYER              0x02
#define TYPE_WALLS               0x03
#define TYPE_PICKUP              0x04
#define TYPE_DOOR                0x05
#define TYPE_KEY                 0x06
#define TYPE_SWAMP               0x07
#define TYPE_MONSTER             0x08
#define TYPE_DRONE               0x09
#define TYPE_VAMPLANT            0x0a
#define TYPE_DIAMOND             0x0b

#endif
