//////////////////////////////////////////////////
// autogenerated

#include "tilesdata.h"
#include "sprtypes.h"

const TileDef tileDefs[]={
    {0x20, TYPE_BACKGROUND, 0, 0, false, "blank.obl"}, // 00 TILES_BLANK
    {0x73, TYPE_STOP, 0, 0, false, "stop.obl"}, // 01 TILES_STOP
    {0x50, TYPE_PLAYER, 0, 0, false, "annie2.obl"}, // 02 TILES_ANNIE2
    {0x23, TYPE_WALLS, 0, 0, false, "walls93.obl"}, // 03 TILES_WALLS93
    {0x25, TYPE_WALLS, 0, 0, false, "walls93.obl"}, // 04 TILES_WALLS93_2
    {0x3d, TYPE_WALLS, 0, 0, false, "walls93.obl"}, // 05 TILES_WALLS93_3
    {0x22, TYPE_WALLS, 0, 0, false, "walls93.obl"}, // 06 TILES_WALLS93_4
    {0x00, TYPE_WALLS, 0, 0, false, "walls93.obl"}, // 07 TILES_WALLS93_5
    {0x00, TYPE_WALLS, 0, 0, false, "walls93.obl"}, // 08 TILES_WALLS93_6
    {0x00, TYPE_WALLS, 0, 0, false, "walls93.obl"}, // 09 TILES_WALLS93_7
    {0x2e, TYPE_WALLS, 0, 0, false, "rock1.obl"}, // 0a TILES_ROCK1
    {0x2c, TYPE_WALLS, 0, 0, false, "rock2.obl"}, // 0b TILES_ROCK2
    {0x3b, TYPE_WALLS, 0, 0, false, "rock3.obl"}, // 0c TILES_ROCK3
    {0x58, TYPE_WALLS, 0, 0, false, "wall_brick.obl"}, // 0d TILES_WALL_BRICK
    {0x57, TYPE_WALLS, 0, 0, false, "wall_brick.obl"}, // 0e TILES_WALL_BRICK_2
    {0x51, TYPE_WALLS, 0, 0, false, "wall_brick.obl"}, // 0f TILES_WALL_BRICK_3
    {0x5a, TYPE_WALLS, 0, 0, false, "wall_brick.obl"}, // 10 TILES_WALL_BRICK_4
    {0x4b, TYPE_WALLS, 0, 0, false, "wall_brick.obl"}, // 11 TILES_WALL_BRICK_5
    {0x55, TYPE_WALLS, 0, 0, false, "wall_brick.obl"}, // 12 TILES_WALL_BRICK_6
    {0x00, TYPE_WALLS, 0, 0, false, "wall_brick.obl"}, // 13 TILES_WALL_BRICK_7
    {0x00, TYPE_WALLS, 0, 0, false, "colorwalls.obl"}, // 14 TILES_COLORWALLS
    {0x00, TYPE_WALLS, 0, 0, false, "colorwalls.obl"}, // 15 TILES_COLORWALLS_2
    {0x00, TYPE_WALLS, 0, 0, false, "colorwalls.obl"}, // 16 TILES_COLORWALLS_3
    {0x00, TYPE_WALLS, 0, 0, false, "colorwalls.obl"}, // 17 TILES_COLORWALLS_4
    {0x00, TYPE_WALLS, 0, 0, false, "colorwalls.obl"}, // 18 TILES_COLORWALLS_5
    {0x00, TYPE_WALLS, 0, 0, false, "colorwalls.obl"}, // 19 TILES_COLORWALLS_6
    {0x00, TYPE_WALLS, 0, 0, false, "colorwalls.obl"}, // 1a TILES_COLORWALLS_7
    {0x00, TYPE_WALLS, 0, 0, false, "colorwalls.obl"}, // 1b TILES_COLORWALLS_8
    {0x00, TYPE_WALLS, 0, 0, false, "colorwalls.obl"}, // 1c TILES_COLORWALLS_9
    {0x00, TYPE_WALLS, 0, 0, false, "colorwalls.obl"}, // 1d TILES_COLORWALLS_A
    {0x00, TYPE_WALLS, 0, 0, false, "colorwalls.obl"}, // 1e TILES_COLORWALLS_B
    {0x00, TYPE_WALLS, 0, 0, false, "colorwalls.obl"}, // 1f TILES_COLORWALLS_C
    {0x00, TYPE_WALLS, 0, 0, false, "colorwalls.obl"}, // 20 TILES_COLORWALLS_D
    {0x00, TYPE_WALLS, 0, 0, false, "colorwalls.obl"}, // 21 TILES_COLORWALLS_E
    {0x00, TYPE_WALLS, 0, 0, false, "colorwalls.obl"}, // 22 TILES_COLORWALLS_F
    {0x00, TYPE_WALLS, 0, 0, false, "colorwalls.obl"}, // 23 TILES_COLORWALLS_10
    {0x70, TYPE_WALLS, 0, 0, false, "pinetree.obl"}, // 24 TILES_PINETREE
    {0x00, TYPE_BACKGROUND, 0, 0, false, "plants.obl"}, // 25 TILES_PLANTS
    {0x00, TYPE_BACKGROUND, 0, 0, false, "plants.obl"}, // 26 TILES_PLANTS_2
    {0x00, TYPE_BACKGROUND, 0, 0, false, "plants.obl"}, // 27 TILES_PLANTS_3
    {0x00, TYPE_BACKGROUND, 0, 0, false, "plants.obl"}, // 28 TILES_PLANTS_4
    {0x00, TYPE_BACKGROUND, 0, 0, false, "plants.obl"}, // 29 TILES_PLANTS_5
    {0x00, TYPE_BACKGROUND, 0, 0, false, "plants.obl"}, // 2a TILES_PLANTS_6
    {0x00, TYPE_BACKGROUND, 0, 0, false, "plants.obl"}, // 2b TILES_PLANTS_7
    {0x3c, TYPE_WALLS, 0, 0, false, "thisway.obl"}, // 2c TILES_THISWAY
    {0x3e, TYPE_WALLS, 0, 0, false, "thisway.obl"}, // 2d TILES_THISWAY_2
    {0x26, TYPE_PICKUP, 3, 0, false, "fruit1.obl"}, // 2e TILES_FRUIT1
    {0x21, TYPE_PICKUP, 15, 8, false, "neckless.obl"}, // 2f TILES_NECKLESS
    {0x61, TYPE_PICKUP, 20, 0, false, "apple.obl"}, // 30 TILES_APPLE
    {0x62, TYPE_PICKUP, 12, 0, false, "book.obl"}, // 31 TILES_BOOK
    {0x42, TYPE_PICKUP, 30, 0, false, "ballon1.obl"}, // 32 TILES_BALLON1
    {0x63, TYPE_PICKUP, 5, 0, false, "carotte.obl"}, // 33 TILES_CAROTTE
    {0x43, TYPE_PICKUP, 5, 0, false, "carotte.obl"}, // 34 TILES_CAROTTE_2
    {0x47, TYPE_PICKUP, 50, 0, false, "chest.obl"}, // 35 TILES_CHEST
    {0x00, TYPE_WALLS, 0, 0, false, "statue.obl"}, // 36 TILES_STATUE
    {0x74, TYPE_WALLS, 0, 0, false, "tomb.obl"}, // 37 TILES_TOMB
    {0x6d, TYPE_WALLS, 0, 0, false, "mushroom.obl"}, // 38 TILES_MUSHROOM
    {0x00, TYPE_PICKUP, 22, 0, false, "small_mush.obl"}, // 39 TILES_SMALL_MUSH
    {0x00, TYPE_PICKUP, 22, 0, false, "small_mush.obl"}, // 3a TILES_SMALL_MUSH_2
    {0x00, TYPE_PICKUP, 22, 0, false, "small_mush.obl"}, // 3b TILES_SMALL_MUSH_3
    {0x00, TYPE_PICKUP, 22, 0, false, "small_mush.obl"}, // 3c TILES_SMALL_MUSH_4
    {0x5b, TYPE_WALLS, 0, 0, false, "pot.obl"}, // 3d TILES_POT
    {0x5d, TYPE_WALLS, 0, 0, false, "pot.obl"}, // 3e TILES_POT_2
    {0x4a, TYPE_WALLS, 0, 0, false, "jar1.obl"}, // 3f TILES_JAR1
    {0x77, TYPE_PICKUP, 16, 0, false, "watermel.obl"}, // 40 TILES_WATERMEL
    {0x00, TYPE_WALLS, 0, 0, false, "boulder.obl"}, // 41 TILES_BOULDER
    {0x00, TYPE_WALLS, 0, 0, false, "boulder.obl"}, // 42 TILES_BOULDER_2
    {0x3f, TYPE_PICKUP, 21, 0, false, "magicbox.obl"}, // 43 TILES_MAGICBOX
    {0x2a, TYPE_PICKUP, 40, 0, false, "magicbot.obl"}, // 44 TILES_MAGICBOT
    {0x00, TYPE_PICKUP, 22, 0, false, "lightbul.obl"}, // 45 TILES_LIGHTBUL
    {0x2b, TYPE_PICKUP, 9, 0, false, "1st_aid.obl"}, // 46 TILES_1ST_AID
    {0x00, TYPE_PICKUP, 27, 0, false, "rope.obl"}, // 47 TILES_ROPE
    {0x53, TYPE_PICKUP, 37, 0, false, "shield.obl"}, // 48 TILES_SHIELD
    {0x6f, TYPE_PICKUP, 44, 0, false, "vials.obl"}, // 49 TILES_VIALS
    {0x00, TYPE_PICKUP, 44, 0, false, "vials.obl"}, // 4a TILES_VIALS_2
    {0x00, TYPE_PICKUP, 44, 0, false, "vials.obl"}, // 4b TILES_VIALS_3
    {0x67, TYPE_PICKUP, 4, 0, false, "poire.obl"}, // 4c TILES_POIRE
    {0x00, TYPE_PICKUP, 45, 0, false, "clover.obl"}, // 4d TILES_CLOVER
    {0x00, TYPE_PICKUP, 32, 0, false, "pumpkin.obl"}, // 4e TILES_PUMPKIN
    {0x40, TYPE_PICKUP, 60, 4, false, "flowers.obl"}, // 4f TILES_FLOWERS
    {0x46, TYPE_PICKUP, 60, 4, false, "flowers.obl"}, // 50 TILES_FLOWERS_2
    {0x48, TYPE_DOOR, 0, 0, false, "heartdoor.obl"}, // 51 TILES_HEARTDOOR
    {0x68, TYPE_KEY, 50, 0, false, "heartkey.obl"}, // 52 TILES_HEARTKEY
    {0x00, TYPE_DOOR, 0, 0, false, "graydoor.obl"}, // 53 TILES_GRAYDOOR
    {0x00, TYPE_KEY, 50, 0, false, "graykey.obl"}, // 54 TILES_GRAYKEY
    {0x00, TYPE_DOOR, 0, 0, false, "popdoor.obl"}, // 55 TILES_POPDOOR
    {0x00, TYPE_KEY, 50, 0, false, "popkey.obl"}, // 56 TILES_POPKEY
    {0x52, TYPE_DOOR, 0, 0, false, "reddoor.obl"}, // 57 TILES_REDDOOR
    {0x72, TYPE_KEY, 50, 0, false, "redkey.obl"}, // 58 TILES_REDKEY
    {0x59, TYPE_DOOR, 0, 0, false, "yeldoor.obl"}, // 59 TILES_YELDOOR
    {0x79, TYPE_KEY, 50, 0, false, "yelkey.obl"}, // 5a TILES_YELKEY
    {0x5e, TYPE_SWAMP, 0, -1, false, "swamp.obl"}, // 5b TILES_SWAMP
    {0x24, TYPE_DIAMOND, 10, 6, false, "diamond.obl"}, // 5c TILES_DIAMOND
    {0x54, TYPE_PICKUP, 99, 20, false, "triforce.obl"}, // 5d TILES_TRIFORCE
    {0x4f, TYPE_PICKUP, 67, 10, false, "orb.obl"}, // 5e TILES_ORB
    {0x00, TYPE_PICKUP, 66, 0, false, "tntstick.obl"}, // 5f TILES_TNTSTICK
    {0x41, TYPE_MONSTER, 0, -20, false, "alpha.obl"}, // 60 TILES_ALPHA
    {0x00, TYPE_MONSTER, 0, -9, false, "blueghos.obl"}, // 61 TILES_BLUEGHOS
    {0x44, TYPE_MONSTER, 0, -4, false, "deico.obl"}, // 62 TILES_DEICO
    {0x2f, TYPE_WALLS, 0, 0, false, "forcef94.obl"}, // 63 TILES_FORCEF94
    {0x5f, TYPE_WALLS, 0, 0, true, "forcefih.obl"}, // 64 TILES_FORCEFIH
    {0x7c, TYPE_WALLS, 0, 0, true, "forcefiv.obl"}, // 65 TILES_FORCEFIV
    {0x69, TYPE_MONSTER, 0, -6, false, "insect1.obl"}, // 66 TILES_INSECT1
    {0x6c, TYPE_MONSTER, 0, -7, false, "lutin.obl"}, // 67 TILES_LUTIN
    {0x4d, TYPE_MONSTER, 0, -8, false, "manka.obl"}, // 68 TILES_MANKA
    {0x00, TYPE_MONSTER, 0, -12, false, "maxkiller.obl"}, // 69 TILES_MAXKILLER
    {0x00, TYPE_MONSTER, 0, -10, false, "octopus.obl"}, // 6a TILES_OCTOPUS
    {0x00, TYPE_MONSTER, 0, -9, false, "ooo.obl"}, // 6b TILES_OOO
    {0x00, TYPE_MONSTER, 0, -10, false, "teddy93.obl"}, // 6c TILES_TEDDY93
    {0x76, TYPE_VAMPLANT, 0, -1, false, "vamplant.obl"}, // 6d TILES_VAMPLANT
    {0x00, TYPE_MONSTER, 0, -6, false, "yahoo.obl"}, // 6e TILES_YAHOO
    {0x00, TYPE_MONSTER, 0, -6, false, "yiga.obl"}, // 6f TILES_YIGA
    {0x00, TYPE_MONSTER, 0, -10, false, "yelkiller.obl"}, // 70 TILES_YELKILLER
    {0x71, TYPE_DRONE, 0, -5, true, "whteworm.obl"}, // 71 TILES_WHTEWORM
    {0x00, TYPE_DRONE, 0, -8, true, "eturtle.obl"}, // 72 TILES_ETURTLE
    {0x00, TYPE_DRONE, 0, -9, true, "drago.obl"}, // 73 TILES_DRAGO
    {0x00, TYPE_DRONE, 0, -10, true, "bird.obl"} // 74 TILES_LEFTBIRD
};

const uint8_t chMap[] = {
     0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
     0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
     0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
     0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
     0x00, 0x2f, 0x06, 0x03, 0x5c, 0x04, 0x2e, 0x00, 
     0x00, 0x00, 0x44, 0x46, 0x0b, 0x00, 0x0a, 0x63, 
     0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
     0x00, 0x00, 0x00, 0x0c, 0x2c, 0x05, 0x2d, 0x43, 
     0x4f, 0x60, 0x32, 0x34, 0x62, 0x00, 0x50, 0x35, 
     0x51, 0x00, 0x3f, 0x11, 0x00, 0x68, 0x00, 0x5e, 
     0x02, 0x0f, 0x57, 0x48, 0x5d, 0x12, 0x00, 0x0e, 
     0x0d, 0x59, 0x10, 0x3d, 0x00, 0x3e, 0x5b, 0x64, 
     0x00, 0x30, 0x31, 0x33, 0x00, 0x00, 0x00, 0x4c, 
     0x52, 0x66, 0x00, 0x00, 0x67, 0x38, 0x00, 0x49, 
     0x24, 0x71, 0x58, 0x01, 0x37, 0x00, 0x6d, 0x40, 
     0x00, 0x5a, 0x00, 0x00, 0x65, 0x00, 0x00, 0x00
};

uint8_t getChTile(const uint8_t i)
{
   return chMap[i % sizeof(chMap)];
}

const TileDef * getTileDefs()
{
  return tileDefs;
}
const TileDef & getTileDef(int i)
{
  return tileDefs[i];
}

