/*
    cs3-runtime-sdl
    Copyright (C) 2025  Francois Blanchette

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

//////////////////////////////////////////////////
// autogenerated

#include <cstddef>
#include "tilesdata.h"
#include "sounds.h"
#include "bossdata.h"

namespace BossData
{
    constexpr auto DEFAULT_HP_COLOR = ORANGE;
    constexpr auto DEFAULT_TEXT_COLOR = RED;
    constexpr int MR_DEMON_MOVING_BASE = 0;
    constexpr int MR_DEMON_MOVING_LEN = 4;
    constexpr int MR_DEMON_ATTACK_BASE = 4;
    constexpr int MR_DEMON_ATTACK_LEN = 8;
    constexpr int MR_DEMON_HURT_BASE = 12;
    constexpr int MR_DEMON_HURT_LEN = 4;
    constexpr int MR_DEMON_DEATH_BASE = 16;
    constexpr int MR_DEMON_DEATH_LEN = 6;
    constexpr int GHOST_IDLE_BASE = 22;
    constexpr int GHOST_IDLE_LEN = 3;
    constexpr int GHOST_MOVING_BASE = 25;
    constexpr int GHOST_MOVING_LEN = 5;
    constexpr int GHOST_ATTACK_BASE = 30;
    constexpr int GHOST_ATTACK_LEN = 6;
    constexpr int GHOST_HURT_BASE = 36;
    constexpr int GHOST_HURT_LEN = 8;
    constexpr int GHOST_DEATH_BASE = 44;
    constexpr int GHOST_DEATH_LEN = 0;
    constexpr int HARPY_ATTACK_BASE = 44;
    constexpr int HARPY_ATTACK_LEN = 8;
    constexpr int HARPY_DEATH_BASE = 52;
    constexpr int HARPY_DEATH_LEN = 6;
    constexpr int HARPY_IDLE_BASE = 58;
    constexpr int HARPY_IDLE_LEN = 4;
    constexpr int HARPY_HURT_BASE = 62;
    constexpr int HARPY_HURT_LEN = 3;
    constexpr int BEHOLDER_ATTACK_BASE = 0;
    constexpr int BEHOLDER_ATTACK_LEN = 8;
    constexpr int BEHOLDER_DEATH_BASE = 32;
    constexpr int BEHOLDER_DEATH_LEN = 5;
    constexpr int BEHOLDER_HURT_BASE = 52;
    constexpr int BEHOLDER_HURT_LEN = 4;
    constexpr int BEHOLDER_MOVING_BASE = 68;
    constexpr int BEHOLDER_MOVING_LEN = 8;
};

using namespace BossData;

constexpr const sprite_hitbox_t g_hitboxes[] = {
    { 47, 1, {{ 0, 5, 3, 3, 2 }, }},
    { 46, 1, {{ 0, 5, 3, 3, 2 }, }},
    { 48, 1, {{ 0, 4, 3, 4, 2 }, }},
    { 1028, 1, {{ 5, 5, 3, 3, 2 }, }},
    { 1029, 1, {{ 5, 5, 3, 3, 2 }, }},
    { 1027, 1, {{ 5, 4, 2, 3, 2 }, }},
    { 1026, 1, {{ 5, 4, 2, 3, 2 }, }},
    { 1025, 1, {{ 5, 4, 2, 3, 2 }, }},
    { 1024, 1, {{ 5, 4, 2, 3, 2 }, }},
    { 1020, 1, {{ 1, 5, 2, 3, 2 }, }},
    { 1019, 1, {{ 1, 5, 2, 2, 2 }, }},
    { 1018, 1, {{ 1, 3, 2, 4, 2 }, }},
    { 1017, 1, {{ 1, 3, 3, 4, 2 }, }},
    { 1016, 1, {{ 1, 4, 3, 3, 2 }, }},
    { 1013, 1, {{ 3, 4, 2, 3, 2 }, }},
    { 1012, 1, {{ 3, 4, 2, 3, 2 }, }},
    { 1011, 1, {{ 3, 4, 2, 3, 2 }, }},
    { 1010, 1, {{ 3, 4, 2, 3, 2 }, }},
    { 1009, 1, {{ 3, 3, 2, 4, 2 }, }},
    { 1008, 1, {{ 3, 4, 2, 3, 2 }, }},
    { 1005, 1, {{ 3, 4, 2, 3, 2 }, }},
    { 1004, 1, {{ 3, 4, 2, 3, 2 }, }},
    { 1003, 1, {{ 3, 4, 2, 3, 2 }, }},
    { 1002, 1, {{ 3, 4, 2, 3, 2 }, }},
    { 1001, 1, {{ 3, 4, 2, 3, 2 }, }},
    { 1000, 1, {{ 3, 4, 2, 3, 2 }, }},
    { 1021, 1, {{ 1, 5, 3, 3, 2 }, }},
};

constexpr const bossData_t g_bossData[] = {
    {
        .name = "Mr. Demon",
        .speed = 3,
        .speed_anime = 3,
        .hp = 64,
        .type = 0xb0,
        .score = 1000,
        .damage = 16,
        .damage_attack = 16,
        .damage_special1 = 16,
        .damage_special2 = 16,
        .flags = BOSS_FLAG_ICE_DAMAGE,
        .path = Path::ASTAR,
        .bullet = TILES_FIREBALL,
        .bullet_rate = 15,
        .bullet_algo = Path::NONE,
        .bullet_sound = SOUND_SHOOT3,
        .bullet_ttl = NoTTL,
        .attack_sound = SOUND_DINOSAUR3,
        .distance_chase = 10,
        .distance_pursuit = 15,
        .distance_attack = 8,
        .is_goal = true,
        .show_details = true,
        .color_hp = ORANGE,
        .color_name = RED,
        .aims = 1,
        .moving = {MR_DEMON_MOVING_BASE, MR_DEMON_MOVING_LEN},
        .attack = {MR_DEMON_ATTACK_BASE, MR_DEMON_ATTACK_LEN},
        .hurt = {MR_DEMON_HURT_BASE, MR_DEMON_HURT_LEN},
        .death = {MR_DEMON_DEATH_BASE, MR_DEMON_DEATH_LEN},
        .idle = {MR_DEMON_MOVING_BASE, MR_DEMON_MOVING_LEN},
        .hitbox = {2, 6, 4, 2 , 0},
        .sheet = 0,
    },
    {
        .name = "Ghost",
        .speed = 4,
        .speed_anime = 4,
        .hp = 64,
        .type = 0xb1,
        .score = 500,
        .damage = 5,
        .damage_attack = 5,
        .damage_special1 = 5,
        .damage_special2 = 5,
        .flags = 0,
        .path = Path::LOS,
        .bullet = TILES_BLANK,
        .bullet_rate = 0,
        .bullet_algo = Path::NONE,
        .bullet_sound = SOUND_NONE,
        .bullet_ttl = NoTTL,
        .attack_sound = SOUND_NONE,
        .distance_chase = 10,
        .distance_pursuit = 20,
        .distance_attack = 5,
        .is_goal = false,
        .show_details = false,
        .color_hp = ORANGE,
        .color_name = RED,
        .aims = 1,
        .moving = {GHOST_MOVING_BASE, GHOST_MOVING_LEN},
        .attack = {GHOST_ATTACK_BASE, GHOST_ATTACK_LEN},
        .hurt = {GHOST_HURT_BASE, GHOST_HURT_LEN},
        .death = {GHOST_DEATH_BASE, GHOST_DEATH_LEN},
        .idle = {GHOST_IDLE_BASE, GHOST_IDLE_LEN},
        .hitbox = {0, 2, 4, 3 , 0},
        .sheet = 0,
    },
    {
        .name = "Harpy",
        .speed = 3,
        .speed_anime = 3,
        .hp = 128,
        .type = 0xb2,
        .score = 1250,
        .damage = 5,
        .damage_attack = 5,
        .damage_special1 = 5,
        .damage_special2 = 5,
        .flags = 0,
        .path = Path::BFS,
        .bullet = TILES_BULLETY1,
        .bullet_rate = 3,
        .bullet_algo = Path::LOS,
        .bullet_sound = SOUND_NONE,
        .bullet_ttl = 20,
        .attack_sound = SOUND_NONE,
        .distance_chase = 10,
        .distance_pursuit = 20,
        .distance_attack = 7,
        .is_goal = true,
        .show_details = true,
        .color_hp = ORANGE,
        .color_name = RED,
        .aims = 1,
        .moving = {HARPY_IDLE_BASE, HARPY_IDLE_LEN},
        .attack = {HARPY_ATTACK_BASE, HARPY_ATTACK_LEN},
        .hurt = {HARPY_HURT_BASE, HARPY_HURT_LEN},
        .death = {HARPY_DEATH_BASE, HARPY_DEATH_LEN},
        .idle = {HARPY_IDLE_BASE, HARPY_IDLE_LEN},
        .hitbox = {2, 6, 2, 2 , 0},
        .sheet = 0,
    },
    {
        .name = "Beholder",
        .speed = 3,
        .speed_anime = 3,
        .hp = 128,
        .type = 0xb3,
        .score = 1250,
        .damage = 9,
        .damage_attack = 9,
        .damage_special1 = 20,
        .damage_special2 = 20,
        .flags = BOSS_FLAG_PROXIMITY_ATTACK,
        .path = Path::BFS,
        .bullet = TILES_BLANK,
        .bullet_rate = 5,
        .bullet_algo = Path::LOS,
        .bullet_sound = SOUND_NONE,
        .bullet_ttl = NoTTL,
        .attack_sound = SOUND_NONE,
        .distance_chase = 10,
        .distance_pursuit = 15,
        .distance_attack = 2,
        .is_goal = true,
        .show_details = true,
        .color_hp = ORANGE,
        .color_name = RED,
        .aims = 4,
        .moving = {BEHOLDER_MOVING_BASE, BEHOLDER_MOVING_LEN},
        .attack = {BEHOLDER_ATTACK_BASE, BEHOLDER_ATTACK_LEN},
        .hurt = {BEHOLDER_HURT_BASE, BEHOLDER_HURT_LEN},
        .death = {BEHOLDER_DEATH_BASE, BEHOLDER_DEATH_LEN},
        .idle = {BEHOLDER_MOVING_BASE, BEHOLDER_MOVING_LEN},
        .hitbox = {3, 5, 2, 2 , 0},
        .sheet = 1,
    },
};
