/*
    cs3-runtime-sdl
    Copyright (C) 2025  Francois Blanchette

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

//////////////////////////////////////////////////
// autogenerated

#include <cstddef>
#include "color.h"
#include "tilesdata.h"
#include "bossdata.h"

namespace BossData
{
    constexpr auto DEFAULT_HP_COLOR = ORANGE;
    constexpr auto DEFAULT_TEXT_COLOR = RED;
    constexpr int MR_DEMON_MOVING_BASE = 0;
    constexpr int MR_DEMON_MOVING_LEN = 4;
    constexpr int MR_DEMON_ATTACK_BASE = 4;
    constexpr int MR_DEMON_ATTACK_LEN = 8;
    constexpr int MR_DEMON_HURT_BASE = 12;
    constexpr int MR_DEMON_HURT_LEN = 4;
    constexpr int MR_DEMON_DEATH_BASE = 16;
    constexpr int MR_DEMON_DEATH_LEN = 6;
    constexpr int GHOST_IDLE_BASE = 22;
    constexpr int GHOST_IDLE_LEN = 3;
    constexpr int GHOST_MOVING_BASE = 25;
    constexpr int GHOST_MOVING_LEN = 5;
    constexpr int GHOST_ATTACK_BASE = 30;
    constexpr int GHOST_ATTACK_LEN = 6;
    constexpr int GHOST_HURT_BASE = 36;
    constexpr int GHOST_HURT_LEN = 7;
    constexpr int GHOST_DEATH_BASE = 43;
    constexpr int GHOST_DEATH_LEN = 0;
};

using namespace BossData;

bossData_t g_bosses[] = {
    {
        .name = "Mr. Demon",
        .speed = 3,
        .a_speed = 3,
        .hp = 64,
        .type = 0xb0,
        .score = 1000,
        .damage = 16,
        .flags = BOSS_FLAG_ICE_DAMAGE,
        .path = ASTAR,
        .bullet = TILES_FIREBALL,
        .bullet_speed = 15,
        .chase_distance = 10,
        .pursuit_distance = 15,
        .is_goal = true,
        .show_details = true,
        .moving = {MR_DEMON_MOVING_BASE, MR_DEMON_MOVING_LEN},
        .attack = {MR_DEMON_ATTACK_BASE, MR_DEMON_ATTACK_LEN},
        .hurt = {MR_DEMON_HURT_BASE, MR_DEMON_HURT_LEN},
        .death = {MR_DEMON_DEATH_BASE, MR_DEMON_DEATH_LEN},
        .idle = {MR_DEMON_MOVING_BASE, MR_DEMON_MOVING_LEN},
        .hitbox = {2, 6, 4, 2},
        .sheet = 0,
    },
    {
        .name = "Ghost",
        .speed = 4,
        .a_speed = 4,
        .hp = 64,
        .type = 0xb1,
        .score = 500,
        .damage = 5,
        .flags = 0,
        .path = LOS,
        .bullet = TILES_BLANK,
        .bullet_speed = 0,
        .chase_distance = 10,
        .pursuit_distance = 20,
        .is_goal = false,
        .show_details = false,
        .moving = {GHOST_MOVING_BASE, GHOST_MOVING_LEN},
        .attack = {GHOST_ATTACK_BASE, GHOST_ATTACK_LEN},
        .hurt = {GHOST_HURT_BASE, GHOST_HURT_LEN},
        .death = {GHOST_DEATH_BASE, GHOST_DEATH_LEN},
        .idle = {GHOST_IDLE_BASE, GHOST_IDLE_LEN},
        .hitbox = {0, 2, 4, 3},
        .sheet = 0,
    },
};

bossData_t *getBossData(const int type)
{
    constexpr size_t bossCount = sizeof(g_bosses) / sizeof(g_bosses[0]);
    for (size_t i = 0; i < bossCount; ++i)
    {
        if (g_bosses[i].type == type)
            return &g_bosses[i];
    }
    return nullptr;
}

