/*
    cs3-runtime-sdl
    Copyright (C) 2025  Francois Blanchette

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

//////////////////////////////////////////////////
// autogenerated

#pragma once

#include <cstdint>
#include "rect.h"

#define FLAG_FIREBALL 0x00000001
#define BOSS_FLAG_ICE_DAMAGE 0x80000000

#define BOSS_MR_DEMON 0xb0
#define BOSS_GHOST 0xb1


namespace BossData
{
    enum Path:uint8_t {
        ASTAR,
        BFS,
        LOS,
        ASTAR_SMOOTH
    };
}

struct boss_seq_t
{
    int base;
    int lenght;
};

struct bossData_t
{
    const char* name;       // boss name
    int speed;              // movement speed
    int a_speed;            // animation speed
    int hp;                 // hp
    int type;               // type
    int score;              // score received
    int damage;             // damage given
    uint32_t flags;         // custom flags
    uint32_t path;          // path finding algo
    uint8_t bullet;         // boss bullet
    uint8_t bullet_speed;   // boss bullet speed
    int chase_distance;     // distance to engage chase
    int pursuit_distance;   // continue pursuit within distance (chase)
    bool is_goal;           // is this boss a map goal?
    bool show_details;      // display hp bar/name
    boss_seq_t moving;      // animation seq: moving
    boss_seq_t attack;      // animation seq: attack
    boss_seq_t hurt;        // animation seq: hurt
    boss_seq_t death;       // animation seq: death
    boss_seq_t idle;        // animation seq: idle
    Rect hitbox;            // boss hitbox
    int sheet;              // sprite sheet used
};

bossData_t *getBossData(const int type);
