/*
    cs3-runtime-sdl
    Copyright (C) 2024  Francois Blanchette

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
// autogenerated

#pragma once
#define CHARS_CUSTOM           0x80
#define CHARS_CUSTOM_BASE      0x5f
#define CHARS_CUR_UP           0x80
#define CHARS_CUR_DOWN         0x81
#define CHARS_CUR_LEFT         0x82
#define CHARS_CUR_RIGHT        0x83
#define CHARS_TUP              0x84
#define CHARS_TDOWN            0x85
#define CHARS_TLEFT            0x86
#define CHARS_TRIGHT           0x87
#define CHARS_DIAMOND          0x88
#define CHARS_STAR             0x89
#define CHARS_CARET            0x8a
#define CHARS_BUTTERFLY        0x8b
#define CHARS_CRUNCH           0x8c
#define CHARS_CHEST            0x8d
#define CHARS_PLAYER           0x8e
#define CHARS_LADDER           0x8f
#define CHARS_SMILEY           0x90
#define CHARS_BRICK            0x91
#define CHARS_WALL             0x92
#define CHARS_CRUSHER          0x93
#define CHARS_COPYRIGHT        0x94
#define CHARS_HEART            0x95
#define CHARS_DIAMOND2         0x96
