/*
    cs3-runtime-sdl
    Copyright (C) 2025 Francois Blanchette

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#include "randomz.h"

// Xorshift PRNG
Random::Random(uint32_t seed, uint32_t tick) : initialSeed_(seed), tick_(tick)
{
    state_ = seed ^ tick;
    if (state_ == 0)
        state_ = 12345; // Avoid zero state
}

uint32_t Random::next()
{
    uint32_t x = state_;
    x ^= x << 13;
    x ^= x >> 17;
    x ^= x << 5;
    state_ = x;
    return x + tick_;
}

int Random::range(int min, int max)
{
    if (min >= max)
        return min;
    return min + (next() % (max - min));
}

void Random::setTick(uint32_t tick)
{
    tick_ = tick;
    state_ = initialSeed_ ^ tick_;
    if (state_ == 0)
        state_ = 12345;
}

void Random::reset()
{
    state_ = initialSeed_ ^ tick_;
    if (state_ == 0)
        state_ = 12345;
}

namespace PrecomputedRandom
{
    const uint32_t table[TABLE_SIZE] = {
#include "random_table.inc" // Generated by script
    };

    uint32_t get(uint32_t tick)
    {
        return table[tick % TABLE_SIZE];
    }
}