/*
    cs3-runtime-sdl
    Copyright (C) 2025 Francois Blanchette

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
//////////////////////////////////////////////////
// autogenerated

#pragma once
#include <cstdint>

// @enum
enum TileAI:uint16_t
{
    AI_STICKY                 = 0x01,
    AI_ROUND                  = 0x02,
    AI_CLASSIC                = 0x02,
    AI_NEO                    = 0x03,
    AI_FOCUS                  = 0x04,
    AI_REVERSE                = 0x08,
    AI_SMART                  = 0x10,
};


// @enum
enum TileFlag:uint16_t
{
    FLAG_GODMODE              = 0x01,
    FLAG_EXTRA_LIFE           = 0x02,
    FLAG_EXTRA_SPEED          = 0x04,
    FLAG_RAGE                 = 0x08,
    FLAG_FRUIT                = 0x1000,
    FLAG_TREASURE             = 0x2000,
    FLAG_ONE_TIME             = 0x4000,
    FLAG_HIDDEN               = 0x8000,
};


// @enum
enum TileSpeed:uint16_t
{
    SPEED_VERYFAST            = 0x02,
    SPEED_FAST                = 0x03,
    SPEED_NORMAL              = 0x04,
    SPEED_SLOW                = 0x05,
    SPEED_VERYSLOW            = 0x06,
};


// @enum
enum TileType:uint8_t
{
    TYPE_BACKGROUND           = 0x00,
    TYPE_STOP                 = 0x01,
    TYPE_PLAYER               = 0x02,
    TYPE_WALLS                = 0x03,
    TYPE_PICKUP               = 0x04,
    TYPE_DOOR                 = 0x05,
    TYPE_KEY                  = 0x06,
    TYPE_SWAMP                = 0x07,
    TYPE_MONSTER              = 0x08,
    TYPE_DRONE                = 0x09,
    TYPE_VAMPLANT             = 0x0a,
    TYPE_DIAMOND              = 0x0b,
    TYPE_ICECUBE              = 0x0c,
    TYPE_FIREBALL             = 0x0d,
    TYPE_BOULDER              = 0x0e,
    TYPE_CHUTE                = 0x0f,
    TYPE_LIGHTNING_BOLT       = 0x10,
    TYPE_FIRE                 = 0x11,
    TYPE_BARREL               = 0x12,
};

