#pragma once

#include "color.h"

// #define BROWN_THEME

#ifdef BROWN_THEME
#define MENU_COLOR_ITEM DARK_BROWN2
#define MENU_COLOR_ITEM_SELECTED PALE_BROWN
#define MENU_COLOR_CURSOR RED_BROWN
#define MENU_COLOR_BORDER DARK_BROWN2
#else
#define MENU_COLOR_ITEM BLUE
#define MENU_COLOR_ITEM_SELECTED YELLOW
#define MENU_COLOR_CURSOR RED
#define MENU_COLOR_BORDER DARKRED
#endif
