/*
    cs3-runtime-sdl
    Copyright (C) 2025 Francois Blanchette

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
//////////////////////////////////////////////////
// autogenerated

#pragma once

#include <cstdint>

typedef struct
{
    uint8_t flags;
    uint8_t type;
    uint8_t score;
    int8_t health;
    uint8_t speed;
    uint8_t ai;
    bool hidden;
    const char * basename;
} TileDef;
uint8_t getChTile(uint8_t i) ;
const TileDef * getTileDefs();
const TileDef & getTileDef(int i);

