/*
    cs3-runtime-sdl
    Copyright (C) 2026 Francois Blanchette

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
//////////////////////////////////////////////////
// autogenerated

#include "tilesdata.h"
#include "tilesdefs.h"
#include "sprtypes.h"

constexpr const TileDef tileDefs[] = {
    // 00 TILES_BLANK
    {.flags=0x00, .type=TYPE_BACKGROUND, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="blank.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 01 TILES_STOP
    {.flags=0x00, .type=TYPE_STOP, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="stop.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 02 TILES_ANNIE2
    {.flags=0x00, .type=TYPE_PLAYER, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="annie_down.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 03 TILES_WALLS93
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="walls93.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 04 TILES_WALLS93_2
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="walls93.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 05 TILES_WALLS93_3
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="walls93.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 06 TILES_WALLS93_4
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="walls93.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 07 TILES_WALLS93_5
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="walls93.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 08 TILES_WALLS93_6
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="walls93.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 09 TILES_WALLS93_7
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="walls93.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 0a TILES_ROCKS0
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="rocks.zip", .bullet=0, .rate=0, .path=0, .range=0},
    // 0b TILES_ROCKS1
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="rocks.zip", .bullet=0, .rate=0, .path=0, .range=0},
    // 0c TILES_ROCKS2
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="rocks.zip", .bullet=0, .rate=0, .path=0, .range=0},
    // 0d TILES_WALL_BRICK
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="wall_brick.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 0e TILES_WALL_BRICK_2
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="wall_brick.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 0f TILES_WALL_BRICK_3
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="wall_brick.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 10 TILES_WALL_BRICK_4
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="wall_brick.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 11 TILES_WALL_BRICK_5
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="wall_brick.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 12 TILES_WALL_BRICK_6
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="wall_brick.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 13 TILES_WALL_BRICK_7
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="wall_brick.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 14 TILES_BRICKS
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="bricks.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 15 TILES_BRICKS_2
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="bricks.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 16 TILES_BRICKS_3
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="bricks.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 17 TILES_BRICKS_4
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="bricks.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 18 TILES_BRICKS_5
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="bricks.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 19 TILES_BRICKS_6
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="bricks.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 1a TILES_BRICKS_7
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="bricks.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 1b TILES_BRICKS_8
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="bricks.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 1c TILES_BRICKS_9
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="bricks.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 1d TILES_BRICKS_A
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="bricks.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 1e TILES_BRICKS_B
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="bricks.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 1f TILES_BRICKS_C
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="bricks.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 20 TILES_BRICKS_D
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="bricks.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 21 TILES_BRICKS_E
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="bricks.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 22 TILES_BRICKS_F
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="bricks.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 23 TILES_BRICKS_10
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="bricks.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 24 TILES_TREE
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="tree.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 25 TILES_PLANTS
    {.flags=0x00, .type=TYPE_BACKGROUND, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="plants.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 26 TILES_PLANTS_2
    {.flags=0x00, .type=TYPE_BACKGROUND, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="plants.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 27 TILES_PLANTS_3
    {.flags=0x00, .type=TYPE_BACKGROUND, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="plants.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 28 TILES_PLANTS_4
    {.flags=0x00, .type=TYPE_BACKGROUND, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="plants.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 29 TILES_PLANTS_5
    {.flags=0x00, .type=TYPE_BACKGROUND, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="plants.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 2a TILES_PLANTS_6
    {.flags=0x00, .type=TYPE_BACKGROUND, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="plants.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 2b TILES_PLANTS_7
    {.flags=0x00, .type=TYPE_BACKGROUND, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="plants.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 2c TILES_THISWAY
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="thisway.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 2d TILES_THISWAY_2
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="thisway.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 2e TILES_POMEGRENADE
    {.flags=0x1000, .type=TYPE_PICKUP, .score=3, .health=0, .speed=0, .ai=0, .hidden=false, .basename="pomegrenade.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 2f TILES_AMULET1
    {.flags=0x2000, .type=TYPE_PICKUP, .score=15, .health=8, .speed=0, .ai=0, .hidden=false, .basename="amulet1.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 30 TILES_APPLE
    {.flags=0x1000, .type=TYPE_PICKUP, .score=20, .health=0, .speed=0, .ai=0, .hidden=false, .basename="apple.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 31 TILES_REDBOOK
    {.flags=0x2000, .type=TYPE_PICKUP, .score=12, .health=0, .speed=0, .ai=0, .hidden=false, .basename="redbook.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 32 TILES_JELLYJAR
    {.flags=0x5000, .type=TYPE_PICKUP, .score=44, .health=0, .speed=0, .ai=0, .hidden=false, .basename="jellyjar.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 33 TILES_STRAWBERRY
    {.flags=0x1000, .type=TYPE_PICKUP, .score=5, .health=0, .speed=0, .ai=0, .hidden=false, .basename="strawberry.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 34 TILES_KIWI
    {.flags=0x1000, .type=TYPE_PICKUP, .score=5, .health=0, .speed=0, .ai=0, .hidden=false, .basename="kiwi.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 35 TILES_CHEST
    {.flags=0x2000, .type=TYPE_PICKUP, .score=50, .health=0, .speed=0, .ai=0, .hidden=false, .basename="chest.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 36 TILES_STATUE
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="statue.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 37 TILES_TOMB5
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="tomb5.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 38 TILES_MUSHROOM
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="mushroom.zip", .bullet=0, .rate=0, .path=0, .range=0},
    // 39 TILES_SMALL_MUSH0
    {.flags=0x4002, .type=TYPE_PICKUP, .score=25, .health=0, .speed=0, .ai=0, .hidden=false, .basename="mush1.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 3a TILES_SMALL_MUSH1
    {.flags=0x4008, .type=TYPE_PICKUP, .score=20, .health=0, .speed=0, .ai=0, .hidden=false, .basename="mush2.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 3b TILES_SMALL_MUSH2
    {.flags=0x4001, .type=TYPE_PICKUP, .score=15, .health=0, .speed=0, .ai=0, .hidden=false, .basename="mush3.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 3c TILES_SMALL_MUSH3
    {.flags=0x4004, .type=TYPE_PICKUP, .score=30, .health=0, .speed=0, .ai=0, .hidden=false, .basename="mush4.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 3d TILES_POT
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="pot.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 3e TILES_POT_2
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="pot.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 3f TILES_JAR1
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="jar1.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 40 TILES_WATERMELON
    {.flags=0x1000, .type=TYPE_PICKUP, .score=16, .health=0, .speed=0, .ai=0, .hidden=false, .basename="watermelon.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 41 TILES_BOULDER
    {.flags=0x00, .type=TYPE_BOULDER, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="boulder.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 42 TILES_BOULDER2
    {.flags=0x00, .type=TYPE_BOULDER, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="boulder.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 43 TILES_GIFTBOX
    {.flags=0x2000, .type=TYPE_PICKUP, .score=21, .health=0, .speed=0, .ai=0, .hidden=false, .basename="giftbox.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 44 TILES_MAGICBOT
    {.flags=0x2000, .type=TYPE_PICKUP, .score=40, .health=0, .speed=0, .ai=0, .hidden=false, .basename="magicbot.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 45 TILES_LIGHTBUL
    {.flags=0x2000, .type=TYPE_PICKUP, .score=22, .health=0, .speed=0, .ai=0, .hidden=false, .basename="lightbul.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 46 TILES_1ST_AID
    {.flags=0x2000, .type=TYPE_PICKUP, .score=9, .health=0, .speed=0, .ai=0, .hidden=false, .basename="1st_aid.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 47 TILES_SCROLL
    {.flags=0x2000, .type=TYPE_PICKUP, .score=27, .health=0, .speed=0, .ai=0, .hidden=false, .basename="scroll.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 48 TILES_SHIELD
    {.flags=0x6000, .type=TYPE_PICKUP, .score=37, .health=0, .speed=0, .ai=0, .hidden=false, .basename="shield.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 49 TILES_POTION1
    {.flags=0x2000, .type=TYPE_PICKUP, .score=44, .health=0, .speed=0, .ai=0, .hidden=false, .basename="potion1.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 4a TILES_POTION2
    {.flags=0x2000, .type=TYPE_PICKUP, .score=22, .health=0, .speed=0, .ai=0, .hidden=false, .basename="potion2.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 4b TILES_POTION3
    {.flags=0x2000, .type=TYPE_PICKUP, .score=33, .health=0, .speed=0, .ai=0, .hidden=false, .basename="potion3.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 4c TILES_PEAR
    {.flags=0x1000, .type=TYPE_PICKUP, .score=4, .health=0, .speed=0, .ai=0, .hidden=false, .basename="pear.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 4d TILES_CLOVER
    {.flags=0x2000, .type=TYPE_PICKUP, .score=45, .health=0, .speed=0, .ai=0, .hidden=false, .basename="clover.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 4e TILES_CHERRY
    {.flags=0x1000, .type=TYPE_PICKUP, .score=32, .health=0, .speed=0, .ai=0, .hidden=false, .basename="cherry.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 4f TILES_FLOWERS
    {.flags=0x2000, .type=TYPE_PICKUP, .score=45, .health=4, .speed=0, .ai=0, .hidden=false, .basename="flowers.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 50 TILES_FLOWERS_2
    {.flags=0x2000, .type=TYPE_PICKUP, .score=35, .health=4, .speed=0, .ai=0, .hidden=false, .basename="flowers.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 51 TILES_DOOR03
    {.flags=0x00, .type=TYPE_DOOR, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="door03.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 52 TILES_KEY03
    {.flags=0x00, .type=TYPE_KEY, .score=50, .health=0, .speed=0, .ai=0, .hidden=false, .basename="key03.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 53 TILES_DOOR01
    {.flags=0x00, .type=TYPE_DOOR, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="door01.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 54 TILES_KEY01
    {.flags=0x00, .type=TYPE_KEY, .score=50, .health=0, .speed=0, .ai=0, .hidden=false, .basename="key01.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 55 TILES_DOOR02
    {.flags=0x00, .type=TYPE_DOOR, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="door02.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 56 TILES_KEY02
    {.flags=0x00, .type=TYPE_KEY, .score=50, .health=0, .speed=0, .ai=0, .hidden=false, .basename="key02.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 57 TILES_DOOR06
    {.flags=0x00, .type=TYPE_DOOR, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="door06.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 58 TILES_KEY06
    {.flags=0x00, .type=TYPE_KEY, .score=50, .health=0, .speed=0, .ai=0, .hidden=false, .basename="key06.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 59 TILES_DOOR04
    {.flags=0x00, .type=TYPE_DOOR, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="door04.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 5a TILES_KEY04
    {.flags=0x00, .type=TYPE_KEY, .score=50, .health=0, .speed=0, .ai=0, .hidden=false, .basename="key04.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 5b TILES_SWAMP
    {.flags=0x00, .type=TYPE_SWAMP, .score=0, .health=-1, .speed=0, .ai=0, .hidden=false, .basename="swamp.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 5c TILES_DIAMOND
    {.flags=0x00, .type=TYPE_DIAMOND, .score=10, .health=6, .speed=0, .ai=0, .hidden=false, .basename="jewel-blue.zip", .bullet=0, .rate=0, .path=0, .range=0},
    // 5d TILES_TRIFORCE
    {.flags=0x6000, .type=TYPE_PICKUP, .score=99, .health=20, .speed=0, .ai=0, .hidden=false, .basename="triforce.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 5e TILES_ORB
    {.flags=0x2000, .type=TYPE_PICKUP, .score=67, .health=10, .speed=0, .ai=0, .hidden=false, .basename="orb.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 5f TILES_TNTSTICK
    {.flags=0x2000, .type=TYPE_PICKUP, .score=66, .health=0, .speed=0, .ai=0, .hidden=false, .basename="tntstick.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 60 TILES_SKELETON
    {.flags=0x00, .type=TYPE_MONSTER, .score=0, .health=-20, .speed=4, .ai=3, .hidden=false, .basename="skeletondn.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 61 TILES_BABYDRAGON
    {.flags=0x00, .type=TYPE_MONSTERV3, .score=0, .health=-9, .speed=4, .ai=3, .hidden=false, .basename="bbdragondn.png", .bullet=TILES_FIREBALL_SM, .rate=16, .path=PATH_ASTAR, .range=7},
    // 62 TILES_DEICO
    {.flags=0x00, .type=TYPE_MONSTER, .score=0, .health=-4, .speed=4, .ai=7, .hidden=false, .basename="deico.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 63 TILES_FORCEF94
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="forcef94.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 64 TILES_FORCEFIH
    {.flags=0x8000, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="forcefih.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 65 TILES_FORCEFIV
    {.flags=0x8000, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="forcefiv.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 66 TILES_INSECT1
    {.flags=0x00, .type=TYPE_MONSTER, .score=0, .health=-6, .speed=5, .ai=1, .hidden=false, .basename="insect1_dn.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 67 TILES_LUTIN
    {.flags=0x00, .type=TYPE_MONSTER, .score=0, .health=-7, .speed=4, .ai=2, .hidden=false, .basename="lutin.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 68 TILES_MANKA
    {.flags=0x00, .type=TYPE_MONSTER, .score=0, .health=-8, .speed=4, .ai=1, .hidden=false, .basename="purplemonster.zip", .bullet=0, .rate=0, .path=0, .range=0},
    // 69 TILES_MUSH_IDLE
    {.flags=0x00, .type=TYPE_MONSTER, .score=0, .health=-6, .speed=4, .ai=11, .hidden=false, .basename="mush-idle.zip", .bullet=0, .rate=0, .path=0, .range=0},
    // 6a TILES_OCTOPUS
    {.flags=0x00, .type=TYPE_MONSTER, .score=0, .health=-10, .speed=4, .ai=2, .hidden=false, .basename="cyclops.zip", .bullet=0, .rate=0, .path=0, .range=0},
    // 6b TILES_OOO
    {.flags=0x00, .type=TYPE_MONSTER, .score=0, .health=-9, .speed=4, .ai=3, .hidden=false, .basename="ooo.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 6c TILES_TEDDY93
    {.flags=0x00, .type=TYPE_MONSTER, .score=0, .health=-10, .speed=4, .ai=2, .hidden=false, .basename="teddy93.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 6d TILES_VAMPLANT
    {.flags=0x00, .type=TYPE_VAMPLANT, .score=0, .health=-1, .speed=3, .ai=0, .hidden=false, .basename="vamplant.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 6e TILES_YAHOO
    {.flags=0x00, .type=TYPE_MONSTER, .score=0, .health=-6, .speed=4, .ai=7, .hidden=false, .basename="yahoo.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 6f TILES_YIGA
    {.flags=0x00, .type=TYPE_MONSTER, .score=0, .health=-6, .speed=4, .ai=3, .hidden=false, .basename="yiga.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 70 TILES_YELKILLER
    {.flags=0x00, .type=TYPE_MONSTER, .score=0, .health=-10, .speed=4, .ai=3, .hidden=false, .basename="yelkiller.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 71 TILES_WHTEWORM
    {.flags=0x8000, .type=TYPE_DRONE, .score=0, .health=-5, .speed=4, .ai=0, .hidden=false, .basename="whteworm.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 72 TILES_ETURTLE
    {.flags=0x8000, .type=TYPE_DRONE, .score=0, .health=-8, .speed=4, .ai=0, .hidden=false, .basename="eturtle.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 73 TILES_DRAGO
    {.flags=0x8000, .type=TYPE_DRONE, .score=0, .health=-9, .speed=4, .ai=0, .hidden=false, .basename="drago.obl", .bullet=0, .rate=0, .path=0, .range=0},
    // 74 TILES_DOORS_LEAF
    {.flags=0x8000, .type=TYPE_BACKGROUND, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="doors_leaf.zip", .bullet=0, .rate=0, .path=0, .range=0},
    // 75 TILES_ICECUBE
    {.flags=0x00, .type=TYPE_ICECUBE, .score=0, .health=0, .speed=3, .ai=0, .hidden=false, .basename="icecube.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 76 TILES_FIREBALL
    {.flags=0x00, .type=TYPE_FIREBALL, .score=0, .health=-20, .speed=4, .ai=0, .hidden=false, .basename="fireball.zip", .bullet=0, .rate=0, .path=0, .range=0},
    // 77 TILES_ICEBOULDER
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="iceboulder.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 78 TILES_ICEMOUNTAIN
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="icemountain.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 79 TILES_SKULL
    {.flags=0x00, .type=TYPE_BOULDER, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="skull.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 7a TILES_COBWEB1
    {.flags=0x00, .type=TYPE_BACKGROUND, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="cobweb1.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 7b TILES_SKULLBN1
    {.flags=0x00, .type=TYPE_BACKGROUND, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="skullbn1.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 7c TILES_SHARD1
    {.flags=0x00, .type=TYPE_BACKGROUND, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="shard1.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 7d TILES_SHARD2
    {.flags=0x00, .type=TYPE_BACKGROUND, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="shard2.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 7e TILES_SHARD3
    {.flags=0x00, .type=TYPE_BACKGROUND, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="shard3.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 7f TILES_SHARD4
    {.flags=0x00, .type=TYPE_BACKGROUND, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="shard4.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 80 TILES_SHARD5
    {.flags=0x00, .type=TYPE_BACKGROUND, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="shard5.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 81 TILES_HRIB1
    {.flags=0x00, .type=TYPE_BACKGROUND, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="hrib1.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 82 TILES_HBONE1
    {.flags=0x00, .type=TYPE_BACKGROUND, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="hbone1.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 83 TILES_HBONE2
    {.flags=0x00, .type=TYPE_BACKGROUND, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="hbone2.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 84 TILES_HXBONE2
    {.flags=0x00, .type=TYPE_BACKGROUND, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="hxbone2.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 85 TILES_HXBONE1
    {.flags=0x00, .type=TYPE_BACKGROUND, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="hxbone1.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 86 TILES_PEBBLE
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="pebble.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 87 TILES_PEBBLE2
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="pebble2.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 88 TILES_ROCKP1
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="rockp1.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 89 TILES_ROCKPEBBLE1
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="rockpebble1.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 8a TILES_TREESTUMP
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="treestump.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 8b TILES_TREESTUMP2
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="treestump2.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 8c TILES_TREESTUMP3
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="treestump3.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 8d TILES_TREESTUMP4
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="treestump4.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 8e TILES_TOMB1
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="tomb1.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 8f TILES_TOMB2
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="tomb2.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 90 TILES_TOMB3
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="tomb3.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 91 TILES_TOMB4
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="tomb4.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 92 TILES_HSKULLBONE1
    {.flags=0x00, .type=TYPE_BACKGROUND, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="hskullbone1.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 93 TILES_HSKULLBONE2
    {.flags=0x00, .type=TYPE_BACKGROUND, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="hskullbone2.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 94 TILES_HSKULL1
    {.flags=0x00, .type=TYPE_BOULDER, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="hskull1.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 95 TILES_CHUTE
    {.flags=0x00, .type=TYPE_CHUTE, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="chute.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 96 TILES_LIGHTNING_BOLT
    {.flags=0x00, .type=TYPE_LIGHTNING_BOLT, .score=0, .health=-10, .speed=4, .ai=0, .hidden=false, .basename="lightning_bolt.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 97 TILES_FIRE
    {.flags=0x00, .type=TYPE_FIRE, .score=0, .health=-1, .speed=0, .ai=0, .hidden=false, .basename="fire.zip", .bullet=0, .rate=0, .path=0, .range=0},
    // 98 TILES_BULLETY1
    {.flags=0x00, .type=TYPE_LIGHTNING_BOLT, .score=0, .health=-10, .speed=3, .ai=0, .hidden=false, .basename="bullety1.zip", .bullet=0, .rate=0, .path=0, .range=0},
    // 99 TILES_BOAT
    {.flags=0x2000, .type=TYPE_PICKUP, .score=125, .health=0, .speed=0, .ai=0, .hidden=false, .basename="boat.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 9a TILES_BARREL2EX
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="barrel2ex.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 9b TILES_BARREL2
    {.flags=0x00, .type=TYPE_BARREL, .score=0, .health=-20, .speed=0, .ai=0, .hidden=false, .basename="barrel2.png", .bullet=0, .rate=0, .path=0, .range=0},
    // 9c TILES_FLAME
    {.flags=0x00, .type=TYPE_FIRE, .score=0, .health=-1, .speed=0, .ai=0, .hidden=false, .basename="flame16x16.zip", .bullet=0, .rate=0, .path=0, .range=0},
    // 9d TILES_EGG_WHOLE
    {.flags=0x00, .type=TYPE_EGG, .score=0, .health=0, .speed=4, .ai=0, .hidden=false, .basename="egg_whole", .bullet=TILES_BABYDRAGON, .rate=0, .path=0, .range=0},
    // 9e TILES_EGG_ROTTEN
    {.flags=0x00, .type=TYPE_WALLS, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="egg_rotten", .bullet=0, .rate=0, .path=0, .range=0},
    // 9f TILES_EGG_CRACKED
    {.flags=0x00, .type=TYPE_BACKGROUND, .score=0, .health=0, .speed=0, .ai=0, .hidden=false, .basename="egg_cracked", .bullet=0, .rate=0, .path=0, .range=0},
    // a0 TILES_FIREBALL_SM
    {.flags=0x00, .type=TYPE_FIREBALL, .score=0, .health=-10, .speed=4, .ai=0, .hidden=false, .basename="fireball_sm.png", .bullet=0, .rate=0, .path=0, .range=0}
};

const uint8_t chMap[] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x2f, 0x06, 0x03, 0x5c, 0x04, 0x2e, 0x00,
    0x00, 0x00, 0x44, 0x46, 0x0b, 0x00, 0x0a, 0x63,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x0c, 0x00, 0x00, 0x00, 0x2c, 0x05, 0x2d, 0x43,
    0x4f, 0x61, 0x32, 0x34, 0x62, 0x00, 0x50, 0x35,
    0x51, 0x00, 0x3f, 0x11, 0x00, 0x68, 0x00, 0x5e,
    0x02, 0x0f, 0x57, 0x48, 0x5d, 0x12, 0x00, 0x0e,
    0x0d, 0x59, 0x10, 0x3d, 0x00, 0x3e, 0x5b, 0x64,
    0x00, 0x30, 0x31, 0x33, 0x60, 0x00, 0x00, 0x4c,
    0x52, 0x66, 0x00, 0x00, 0x67, 0x38, 0x00, 0x49,
    0x24, 0x71, 0x58, 0x01, 0x37, 0x00, 0x6d, 0x40,
    0x00, 0x5a, 0x00, 0x00, 0x65, 0x00, 0x00, 0x00,
};

uint8_t getChTile(const uint8_t i)
{
  return chMap[i % sizeof(chMap)];
}

