/*
    cs3-runtime-sdl
    Copyright (C) 2025 Francois Blanchette

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
//////////////////////////////////////////////////
// autogenerated

#pragma once
#include <cinttypes>
#include <string>
#include <unordered_map>

std::string get_tileNames(const uint16_t i);
const std::unordered_map<uint16_t, std::string> & get_tileNamesMap();
std::string get_aiNames(const uint16_t i);
const std::unordered_map<uint16_t, std::string> & get_aiNamesMap();
std::string get_flagsNames(const uint16_t i);
const std::unordered_map<uint16_t, std::string> & get_flagsNamesMap();
std::string get_speedsNames(const uint16_t i);
const std::unordered_map<uint16_t, std::string> & get_speedsNamesMap();
std::string get_typesNames(const uint16_t i);
const std::unordered_map<uint16_t, std::string> & get_typesNamesMap();

