/*
    cs3-runtime-sdl
    Copyright (C) 2025 Francois Blanchette

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
//////////////////////////////////////////////////
// autogenerated

#pragma once

#define ANIMZ_SWAMP_LEN      0x02
#define ANIMZ_DIAMOND_LEN    0x0d
#define ANIMZ_ALPHA_LEN      0x02
#define ANIMZ_BLUEGHOS_LEN   0x01
#define ANIMZ_DEICO_LEN      0x02
#define ANIMZ_FORCEF94_LEN   0x08
#define ANIMZ_INSECT1_LEN    0x08
#define ANIMZ_INSECT1_DN_LEN 0x08
#define ANIMZ_INSECT1_LF_LEN 0x08
#define ANIMZ_INSECT1_RG_LEN 0x08
#define ANIMZ_LUTIN_LEN      0x02
#define ANIMZ_MANKA_LEN      0x02
#define ANIMZ_MAXKILLER_LEN  0x02
#define ANIMZ_OCTOPUS_LEN    0x02
#define ANIMZ_OOO_LEN        0x02
#define ANIMZ_TEDDY93_LEN    0x02
#define ANIMZ_VAMPLANT_LEN   0x02
#define ANIMZ_YAHOO_LEN      0x02
#define ANIMZ_YIGA_LEN       0x02
#define ANIMZ_YELKILLER_LEN  0x02
#define ANIMZ_ORB_LEN        0x04
#define ANIMZ_TRIFORCE_LEN   0x04
#define ANIMZ_SPARKLE_LEN    0x08
#define ANIMZ_MUSHROOM_LEN   0x03
#define ANIMZ_MUSH_DOWN_LEN  0x03
#define ANIMZ_MUSH_LEFT_LEN  0x03
#define ANIMZ_MUSH_RIGHT_LEN 0x03
#define ANIMZ_MUSHROOM_IDLE_LEN 0x04

#define ANIMZ_SWAMP          0x00
#define ANIMZ_SWAMP_2        0x01
#define ANIMZ_DIAMOND        0x02
#define ANIMZ_DIAMOND_2      0x03
#define ANIMZ_DIAMOND_3      0x04
#define ANIMZ_DIAMOND_4      0x05
#define ANIMZ_DIAMOND_5      0x06
#define ANIMZ_DIAMOND_6      0x07
#define ANIMZ_DIAMOND_7      0x08
#define ANIMZ_DIAMOND_8      0x09
#define ANIMZ_DIAMOND_9      0x0a
#define ANIMZ_DIAMOND_A      0x0b
#define ANIMZ_DIAMOND_B      0x0c
#define ANIMZ_DIAMOND_C      0x0d
#define ANIMZ_DIAMOND_D      0x0e
#define ANIMZ_ALPHA          0x0f
#define ANIMZ_ALPHA_2        0x10
#define ANIMZ_BLUEGHOS       0x11
#define ANIMZ_DEICO          0x12
#define ANIMZ_DEICO_2        0x13
#define ANIMZ_FORCEF94       0x14
#define ANIMZ_FORCEF94_2     0x15
#define ANIMZ_FORCEF94_3     0x16
#define ANIMZ_FORCEF94_4     0x17
#define ANIMZ_FORCEF94_5     0x18
#define ANIMZ_FORCEF94_6     0x19
#define ANIMZ_FORCEF94_7     0x1a
#define ANIMZ_FORCEF94_8     0x1b
#define ANIMZ_INSECT1        0x1c
#define ANIMZ_INSECT1_2      0x1d
#define ANIMZ_INSECT1_3      0x1e
#define ANIMZ_INSECT1_4      0x1f
#define ANIMZ_INSECT1_5      0x20
#define ANIMZ_INSECT1_6      0x21
#define ANIMZ_INSECT1_7      0x22
#define ANIMZ_INSECT1_8      0x23
#define ANIMZ_INSECT1_DN     0x24
#define ANIMZ_INSECT1_DN_2   0x25
#define ANIMZ_INSECT1_DN_3   0x26
#define ANIMZ_INSECT1_DN_4   0x27
#define ANIMZ_INSECT1_DN_5   0x28
#define ANIMZ_INSECT1_DN_6   0x29
#define ANIMZ_INSECT1_DN_7   0x2a
#define ANIMZ_INSECT1_DN_8   0x2b
#define ANIMZ_INSECT1_LF     0x2c
#define ANIMZ_INSECT1_LF_2   0x2d
#define ANIMZ_INSECT1_LF_3   0x2e
#define ANIMZ_INSECT1_LF_4   0x2f
#define ANIMZ_INSECT1_LF_5   0x30
#define ANIMZ_INSECT1_LF_6   0x31
#define ANIMZ_INSECT1_LF_7   0x32
#define ANIMZ_INSECT1_LF_8   0x33
#define ANIMZ_INSECT1_RG     0x34
#define ANIMZ_INSECT1_RG_2   0x35
#define ANIMZ_INSECT1_RG_3   0x36
#define ANIMZ_INSECT1_RG_4   0x37
#define ANIMZ_INSECT1_RG_5   0x38
#define ANIMZ_INSECT1_RG_6   0x39
#define ANIMZ_INSECT1_RG_7   0x3a
#define ANIMZ_INSECT1_RG_8   0x3b
#define ANIMZ_LUTIN          0x3c
#define ANIMZ_LUTIN_2        0x3d
#define ANIMZ_MANKA          0x3e
#define ANIMZ_MANKA_2        0x3f
#define ANIMZ_MAXKILLER      0x40
#define ANIMZ_OCTOPUS        0x41
#define ANIMZ_OCTOPUS_2      0x42
#define ANIMZ_OOO            0x43
#define ANIMZ_OOO_2          0x44
#define ANIMZ_TEDDY93        0x45
#define ANIMZ_TEDDY93_2      0x46
#define ANIMZ_VAMPLANT       0x47
#define ANIMZ_VAMPLANT_2     0x48
#define ANIMZ_YAHOO          0x49
#define ANIMZ_YAHOO_2        0x4a
#define ANIMZ_YIGA           0x4b
#define ANIMZ_YIGA_2         0x4c
#define ANIMZ_YELKILLER      0x4d
#define ANIMZ_YELKILLER_2    0x4e
#define ANIMZ_ORB            0x4f
#define ANIMZ_ORB_2          0x50
#define ANIMZ_ORB_3          0x51
#define ANIMZ_ORB_4          0x52
#define ANIMZ_TRIFORCE       0x53
#define ANIMZ_TRIFORCE_2     0x54
#define ANIMZ_TRIFORCE_3     0x55
#define ANIMZ_TRIFORCE_4     0x56
#define ANIMZ_SPARKLE        0x57
#define ANIMZ_SPARKLE_2      0x58
#define ANIMZ_SPARKLE_3      0x59
#define ANIMZ_SPARKLE_4      0x5a
#define ANIMZ_SPARKLE_5      0x5b
#define ANIMZ_SPARKLE_6      0x5c
#define ANIMZ_SPARKLE_7      0x5d
#define ANIMZ_SPARKLE_8      0x5e
#define ANIMZ_MUSHROOM       0x5f
#define ANIMZ_MUSHROOM_2     0x60
#define ANIMZ_MUSHROOM_3     0x61
#define ANIMZ_MUSH_DOWN      0x62
#define ANIMZ_MUSH_DOWN_2    0x63
#define ANIMZ_MUSH_DOWN_3    0x64
#define ANIMZ_MUSH_LEFT      0x65
#define ANIMZ_MUSH_LEFT_2    0x66
#define ANIMZ_MUSH_LEFT_3    0x67
#define ANIMZ_MUSH_RIGHT     0x68
#define ANIMZ_MUSH_RIGHT_2   0x69
#define ANIMZ_MUSH_RIGHT_3   0x6a
#define ANIMZ_MUSHROOM_IDLE  0x6b
#define ANIMZ_MUSHROOM_IDLE_2 0x6c
#define ANIMZ_MUSHROOM_IDLE_3 0x6d
#define ANIMZ_MUSHROOM_IDLE_4 0x6e
