/*
    cs3-runtime-sdl
    Copyright (C) 2025 Francois Blanchette

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
//////////////////////////////////////////////////
// autogenerated

#pragma once

#define ANNIE_ANNIE2_LEN          0x08
#define ANNIE_ANNIE_DOWN_LEN      0x08
#define ANNIE_ANNIE_LEFT_LEN      0x08
#define ANNIE_ANNIE_RG_LEN        0x08
#define ANNIE_ANNIE_DEAD_LEN      0x08
#define ANNIE_ANNIE_IDLE_LEN      0x01
#define ANNIE_ANNIE_IDLE2_LEN     0x01
#define ANNIE_ANNIE_IDLE3_LEN     0x01
#define ANNIE_ANNIE_IDLE4_LEN     0x01

#define ANNIE_ANNIE2              0x00
#define ANNIE_ANNIE2_2            0x01
#define ANNIE_ANNIE2_3            0x02
#define ANNIE_ANNIE2_4            0x03
#define ANNIE_ANNIE2_5            0x04
#define ANNIE_ANNIE2_6            0x05
#define ANNIE_ANNIE2_7            0x06
#define ANNIE_ANNIE2_8            0x07
#define ANNIE_ANNIE_DOWN          0x08
#define ANNIE_ANNIE_DOWN_2        0x09
#define ANNIE_ANNIE_DOWN_3        0x0a
#define ANNIE_ANNIE_DOWN_4        0x0b
#define ANNIE_ANNIE_DOWN_5        0x0c
#define ANNIE_ANNIE_DOWN_6        0x0d
#define ANNIE_ANNIE_DOWN_7        0x0e
#define ANNIE_ANNIE_DOWN_8        0x0f
#define ANNIE_ANNIE_LEFT          0x10
#define ANNIE_ANNIE_LEFT_2        0x11
#define ANNIE_ANNIE_LEFT_3        0x12
#define ANNIE_ANNIE_LEFT_4        0x13
#define ANNIE_ANNIE_LEFT_5        0x14
#define ANNIE_ANNIE_LEFT_6        0x15
#define ANNIE_ANNIE_LEFT_7        0x16
#define ANNIE_ANNIE_LEFT_8        0x17
#define ANNIE_ANNIE_RG            0x18
#define ANNIE_ANNIE_RG_2          0x19
#define ANNIE_ANNIE_RG_3          0x1a
#define ANNIE_ANNIE_RG_4          0x1b
#define ANNIE_ANNIE_RG_5          0x1c
#define ANNIE_ANNIE_RG_6          0x1d
#define ANNIE_ANNIE_RG_7          0x1e
#define ANNIE_ANNIE_RG_8          0x1f
#define ANNIE_ANNIE_DEAD          0x20
#define ANNIE_ANNIE_DEAD_2        0x21
#define ANNIE_ANNIE_DEAD_3        0x22
#define ANNIE_ANNIE_DEAD_4        0x23
#define ANNIE_ANNIE_DEAD_5        0x24
#define ANNIE_ANNIE_DEAD_6        0x25
#define ANNIE_ANNIE_DEAD_7        0x26
#define ANNIE_ANNIE_DEAD_8        0x27
#define ANNIE_ANNIE_IDLE          0x28
#define ANNIE_ANNIE_IDLE2         0x29
#define ANNIE_ANNIE_IDLE3         0x2a
#define ANNIE_ANNIE_IDLE4         0x2b
#define ANNIE_TOTAL_COUNT         0x2c
