//////////////////////////////////////////////////
// autogenerated

#define SOUND_NONE                 0x00
#define SOUND_CRAWL                0x01
#define SOUND_GRUUP                0x02
#define SOUND_SHOOT                0x03
#define SOUND_SPLAT                0x04
#define SOUND_DOOR                 0x05
#define SOUND_KEY                  0x06
#define SOUND_POW                  0x07
#define SOUND_DEATH_MUSIC          0x08
#define SOUND_LEAP                 0x09
#define SOUND_BELLS1               0x0a
#define SOUND_LASER                0x0b
#define SOUND_CLICK4               0x0c
#define SOUND_0009                 0x0d
#define SOUND_COIN1                0x0e
#define SOUND_OKAY                 0x0f
