//////////////////////////////////////////////////
// autogenerated

#ifndef _SPRTYPES__H
#define _SPRTYPES__H

#define AI_STICKY                0x01
#define AI_ROUND                 0x02
#define AI_CLASSIC               0x02
#define AI_NEO                   0x03
#define AI_FOCUS                 0x04

#define FLAG_GODMODE             0x01
#define FLAG_EXTRA_LIFE          0x02
#define FLAG_EXTRA_SPEED         0x04

#define SPEED_FAST               0x03
#define SPEED_NORMAL             0x04
#define SPEED_SLOW               0x05
#define SPEED_VERYSLOW           0x06

#define TYPE_BACKGROUND          0x00
#define TYPE_STOP                0x01
#define TYPE_PLAYER              0x02
#define TYPE_WALLS               0x03
#define TYPE_PICKUP              0x04
#define TYPE_DOOR                0x05
#define TYPE_KEY                 0x06
#define TYPE_SWAMP               0x07
#define TYPE_MONSTER             0x08
#define TYPE_DRONE               0x09
#define TYPE_VAMPLANT            0x0a
#define TYPE_DIAMOND             0x0b

#endif
