/*
    cs3-runtime-sdl
    Copyright (C) 2025 Francois Blanchette

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
//////////////////////////////////////////////////
// autogenerated

#pragma once

#define AI_STICKY                0x01
#define AI_ROUND                 0x02
#define AI_CLASSIC               0x02
#define AI_NEO                   0x03
#define AI_FOCUS                 0x04
#define AI_REVERSE               0x08

#define FLAG_GODMODE             0x01
#define FLAG_EXTRA_LIFE          0x02
#define FLAG_EXTRA_SPEED         0x04
#define FLAG_RAGE                0x08

#define SPEED_FAST               0x03
#define SPEED_NORMAL             0x04
#define SPEED_SLOW               0x05
#define SPEED_VERYSLOW           0x06

#define TYPE_BACKGROUND          0x00
#define TYPE_STOP                0x01
#define TYPE_PLAYER              0x02
#define TYPE_WALLS               0x03
#define TYPE_PICKUP              0x04
#define TYPE_DOOR                0x05
#define TYPE_KEY                 0x06
#define TYPE_SWAMP               0x07
#define TYPE_MONSTER             0x08
#define TYPE_DRONE               0x09
#define TYPE_VAMPLANT            0x0a
#define TYPE_DIAMOND             0x0b
