/*
    cs3-runtime-sdl
    Copyright (C) 2025 Francois Blanchette

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
//////////////////////////////////////////////////
// autogenerated

#include <unordered_map>
#include <string>
#include "tilesdata.h"
#include "sprtypes.h"

#define _S(_x) {_x, #_x}

static const std::unordered_map<uint16_t, std::string> g_tileNames = {
    _S(TILES_BLANK),
    _S(TILES_STOP),
    _S(TILES_ANNIE2),
    _S(TILES_WALLS93),
    _S(TILES_WALLS93_2),
    _S(TILES_WALLS93_3),
    _S(TILES_WALLS93_4),
    _S(TILES_WALLS93_5),
    _S(TILES_WALLS93_6),
    _S(TILES_WALLS93_7),
    _S(TILES_ROCK1),
    _S(TILES_ROCK2),
    _S(TILES_ROCK3),
    _S(TILES_WALL_BRICK),
    _S(TILES_WALL_BRICK_2),
    _S(TILES_WALL_BRICK_3),
    _S(TILES_WALL_BRICK_4),
    _S(TILES_WALL_BRICK_5),
    _S(TILES_WALL_BRICK_6),
    _S(TILES_WALL_BRICK_7),
    _S(TILES_BRICKS),
    _S(TILES_BRICKS_2),
    _S(TILES_BRICKS_3),
    _S(TILES_BRICKS_4),
    _S(TILES_BRICKS_5),
    _S(TILES_BRICKS_6),
    _S(TILES_BRICKS_7),
    _S(TILES_BRICKS_8),
    _S(TILES_BRICKS_9),
    _S(TILES_BRICKS_A),
    _S(TILES_BRICKS_B),
    _S(TILES_BRICKS_C),
    _S(TILES_BRICKS_D),
    _S(TILES_BRICKS_E),
    _S(TILES_BRICKS_F),
    _S(TILES_BRICKS_10),
    _S(TILES_TREE),
    _S(TILES_PLANTS),
    _S(TILES_PLANTS_2),
    _S(TILES_PLANTS_3),
    _S(TILES_PLANTS_4),
    _S(TILES_PLANTS_5),
    _S(TILES_PLANTS_6),
    _S(TILES_PLANTS_7),
    _S(TILES_THISWAY),
    _S(TILES_THISWAY_2),
    _S(TILES_POMEGRENADE),
    _S(TILES_AMULET1),
    _S(TILES_APPLE),
    _S(TILES_REDBOOK),
    _S(TILES_JELLYJAR),
    _S(TILES_STRAWBERRY),
    _S(TILES_KIWI),
    _S(TILES_CHEST),
    _S(TILES_STATUE),
    _S(TILES_TOMB),
    _S(TILES_MUSHROOM),
    _S(TILES_SMALL_MUSH0),
    _S(TILES_SMALL_MUSH1),
    _S(TILES_SMALL_MUSH2),
    _S(TILES_SMALL_MUSH3),
    _S(TILES_POT),
    _S(TILES_POT_2),
    _S(TILES_JAR1),
    _S(TILES_WATERMELON),
    _S(TILES_BOULDER),
    _S(TILES_BOULDER2),
    _S(TILES_GIFTBOX),
    _S(TILES_MAGICBOT),
    _S(TILES_LIGHTBUL),
    _S(TILES_1ST_AID),
    _S(TILES_SCROLL),
    _S(TILES_SHIELD),
    _S(TILES_POTION1),
    _S(TILES_POTION2),
    _S(TILES_POTION3),
    _S(TILES_PEAR),
    _S(TILES_CLOVER),
    _S(TILES_CHERRY),
    _S(TILES_FLOWERS),
    _S(TILES_FLOWERS_2),
    _S(TILES_DOOR03),
    _S(TILES_KEY03),
    _S(TILES_DOOR01),
    _S(TILES_KEY01),
    _S(TILES_DOOR02),
    _S(TILES_KEY02),
    _S(TILES_DOOR06),
    _S(TILES_KEY06),
    _S(TILES_DOOR04),
    _S(TILES_KEY04),
    _S(TILES_SWAMP),
    _S(TILES_DIAMOND),
    _S(TILES_TRIFORCE),
    _S(TILES_ORB),
    _S(TILES_TNTSTICK),
    _S(TILES_ALPHA),
    _S(TILES_BLUEGHOS),
    _S(TILES_DEICO),
    _S(TILES_FORCEF94),
    _S(TILES_FORCEFIH),
    _S(TILES_FORCEFIV),
    _S(TILES_INSECT1),
    _S(TILES_LUTIN),
    _S(TILES_MANKA),
    _S(TILES_MUSH_IDLE),
    _S(TILES_OCTOPUS),
    _S(TILES_OOO),
    _S(TILES_TEDDY93),
    _S(TILES_VAMPLANT),
    _S(TILES_YAHOO),
    _S(TILES_YIGA),
    _S(TILES_YELKILLER),
    _S(TILES_WHTEWORM),
    _S(TILES_ETURTLE),
    _S(TILES_DRAGO),
    _S(TILES_DOORS_LEAF),
};

static const std::unordered_map<uint16_t, std::string> g_aiNames = {
    _S(AI_STICKY),
    _S(AI_CLASSIC),
    _S(AI_ROUND),
    _S(AI_NEO),
    _S(AI_FOCUS),
    _S(AI_REVERSE),
};

static const std::unordered_map<uint16_t, std::string> g_flagsNames = {
    _S(FLAG_GODMODE),
    _S(FLAG_EXTRA_LIFE),
    _S(FLAG_EXTRA_SPEED),
    _S(FLAG_RAGE),
};

static const std::unordered_map<uint16_t, std::string> g_speedsNames = {
    _S(SPEED_VERYFAST),
    _S(SPEED_FAST),
    _S(SPEED_NORMAL),
    _S(SPEED_SLOW),
    _S(SPEED_VERYSLOW),
};

static const std::unordered_map<uint16_t, std::string> g_typesNames = {
    _S(TYPE_BACKGROUND),
    _S(TYPE_STOP),
    _S(TYPE_PLAYER),
    _S(TYPE_WALLS),
    _S(TYPE_PICKUP),
    _S(TYPE_DOOR),
    _S(TYPE_KEY),
    _S(TYPE_SWAMP),
    _S(TYPE_MONSTER),
    _S(TYPE_DRONE),
    _S(TYPE_VAMPLANT),
    _S(TYPE_DIAMOND),
};

std::string get_tileNames(const uint16_t i)
{
    const auto &it = g_tileNames.find(i);
    if (it != g_tileNames.end())
        return it->second;
    else
        return "";
}

const std::unordered_map<uint16_t, std::string> & get_tileNamesMap()
{
   return g_tileNames;
}

std::string get_aiNames(const uint16_t i)
{
    const auto &it = g_aiNames.find(i);
    if (it != g_aiNames.end())
        return it->second;
    else
        return "";
}

const std::unordered_map<uint16_t, std::string> & get_aiNamesMap()
{
   return g_aiNames;
}

std::string get_flagsNames(const uint16_t i)
{
    const auto &it = g_flagsNames.find(i);
    if (it != g_flagsNames.end())
        return it->second;
    else
        return "";
}

const std::unordered_map<uint16_t, std::string> & get_flagsNamesMap()
{
   return g_flagsNames;
}

std::string get_speedsNames(const uint16_t i)
{
    const auto &it = g_speedsNames.find(i);
    if (it != g_speedsNames.end())
        return it->second;
    else
        return "";
}

const std::unordered_map<uint16_t, std::string> & get_speedsNamesMap()
{
   return g_speedsNames;
}

std::string get_typesNames(const uint16_t i)
{
    const auto &it = g_typesNames.find(i);
    if (it != g_typesNames.end())
        return it->second;
    else
        return "";
}

const std::unordered_map<uint16_t, std::string> & get_typesNamesMap()
{
   return g_typesNames;
}

