name: Windows Release

on:
  push:
    branches:
      - "master"
      - "develop"
    tags:
      - "v*"
  pull_request:
    branches:
      - "master"

defaults:
  run:
    shell: bash

env:
  BUILD_TYPE: Release
  SOURCE_DIR: ${{ github.workspace }}
  #QT_VERSION: 6.5.3
  QT_VERSION: 6.7.1
  ARTIFACT: CS3MapEdit_Win64
  ARCH: win64_msvc2019_64
  HOST: windows

jobs:
  build:
    runs-on: windows-2022 # Use the Windows Server 2022 runner

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: (2) Get all tags for correct version determination
        working-directory: ${{ github.workspace }}
        run: |
          git fetch --all --tags -f

      - name: Set up Python
        uses: actions/setup-python@v5 # Action to set up Python
        with:
          python-version: "3.9" # Specify the desired Python version (e.g., '3.9', '3.10', '3.x')
          architecture: "x64" # Specify the architecture (optional, defaults to host OS architecture)

      - name: Run Python script
        run: |
          python bin/patch.py

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: ${{ env.HOST }}
          target: desktop
          arch: ${{ env.ARCH }}
          dir: ${{ runner.temp }}
          #modules: qtcharts qt3d
          setup-python: false

      - name: Configure build with CMake
        working-directory: ${{ env.SOURCE_DIR }}
        run: |
          cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        working-directory: ${{ env.SOURCE_DIR }}
        run: |
          cmake --build build

      - name: Deploy Qt runtime
        working-directory: ${{ env.SOURCE_DIR }}/build
        run: |
          windeployqt --pdb --release --no-compiler-runtime --no-translations mapedit.exe --qmldir=${{ env.SOURCE_DIR }}/src

      - name: Compress to zip file
        working-directory: ${{ env.SOURCE_DIR }}/build
        run: |
          7z a ${{ env.SOURCE_DIR }}/${{ env.ARTIFACT }}.zip build

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            LICENSE
            *.zip

      - name: Save build artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.SOURCE_DIR }}/build
          retention-days: 7
